server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finance_schedule_hub?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 2005
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true